version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_abm_rest
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  crud-rest:
    container_name: service-crud
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    env_file: ./.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

volumes:
  data-mysql:
    name: data-mysql

networks:
  spring:
    name: spring